language: rust
os:
- linux
- osx
rust:
- nightly
- stable
matrix:
  allow_failures:
  - os: linux
    rust: nightly
  - os: osx
    rust: nightly
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - libsdl2-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev
before_install:
- 'if [[ "$TRAVIS_OS_NAME" != linux ]]; then brew update; fi'
install:
- 'if [[ "$TRAVIS_OS_NAME" != linux ]]; then brew install sdl2; fi'
  # Upgrade SDL. Copy-paste from https://github.com/libtcod/libtcod/blob/master/.ci/travis_before_install.sh @ ce85b9f0245ece439e509fc38667aa59c440d391
- 'if [[ "$TRAVIS_OS_NAME" == linux ]]; then wget -O - https://www.libsdl.org/release/SDL2-2.0.8.tar.gz | tar xz; fi'
- 'if [[ "$TRAVIS_OS_NAME" == linux ]]; then (cd SDL2-* && ./configure --prefix=$HOME/.local && make -j 3 install); fi'
- 'if [[ "$TRAVIS_OS_NAME" == linux ]]; then PATH=~/.local/bin:$PATH; PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$HOME/.local/lib/pkgconfig"; fi'

script:
- cargo build --verbose
- cargo test --verbose
- cargo test --features "rustc-serialize serde" --verbose
- cargo test --release
after_success: ! '[ $TRAVIS_BRANCH = master ] &&

  [ "$TRAVIS_OS_NAME" = linux ] &&

  [ $TRAVIS_PULL_REQUEST = false ] &&

  cargo doc &&

  echo ''<meta http-equiv=refresh content="0;url=tcod/index.html">'' > target/doc/index.html
  &&

  git config --global user.email "travis@travis-ci.org" &&

  git config --global user.name "travis-ci" &&

  sudo pip install ghp-import &&

  ghp-import -n target/doc &&

  git push -fq https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages

'
env:
  global:
  - secure: h21kqC5s6iVs4p5n9KFZ5ZTWtPF8nGVFpaPP6t/1Sg+xMaHMDyr/sBYI1gsNGTXrVsiP2Zs6cRTBEbX12PVL6MXFgKpdhKG1+lBCMk6HxU8/W2UHCh6Y38+W4Ybyv5fuoWqkUOX3yODNkRZWrqNhdm8lCdE2uGczkIKPi7hDYMM=
  - CC=gcc-8
  - CXX=g++-8
